"""add bill id in notification

Revision ID: 129afb3e4bd3
Revises: de19ab89e1db
Create Date: 2025-08-28 17:31:35.602502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129afb3e4bd3'
down_revision: Union[str, Sequence[str], None] = 'de19ab89e1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('bill_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'bill_info', ['bill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'bill_id')
    # ### end Alembic commands ###
